#!/bin/bash
clear
rm -f ./output/*.zip
rm -rf ./output/boot
rm -rf ./output/system/lib/modules
mkdir -p ./output/system/lib/modules
mkdir -p ./output/boot
#./mkbootfs ./ramdisk | gzip > ramdisk.gz
cp ramdisk.cpio.lz4 ./output/boot
cd kernel10c
export CROSS_COMPILE=../linaro-4.9-cortex-a15/bin/arm-cortex_a15-linux-gnueabihf-
export USE_CCACHE=1
export ARCH=arm
rm -f ./arch/arm/boot/dt.img
rm -f ./arch/arm/boot/*.dtb
make clean -j4
make -j16
./scripts/dtc/dtc -p 1024 -O dtb -o ./arch/arm/boot/msm8974-g2-dcm.dtb ./arch/arm/boot/dts/msm8974-g2-dcm/msm8974-g2-dcm.dts
./scripts/dtc/dtc -p 1024 -O dtb -o ./arch/arm/boot/msm8974-v2-g2-dcm.dtb ./arch/arm/boot/dts/msm8974-g2-dcm/msm8974-v2-g2-dcm.dts
./scripts/dtc/dtc -p 1024 -O dtb -o ./arch/arm/boot/msm8974-v2-2-g2-dcm.dtb ./arch/arm/boot/dts/msm8974-g2-dcm/msm8974-v2-2-g2-dcm.dts
./scripts/dtbTool -s 2048 -o ./arch/arm/boot/dt.img -p ./scripts/dtc/ ./arch/arm/boot/
cd ../
cp ./kernel10c/scripts/mkbootimg ./output/boot
find . -name '*.ko' -exec cp {} ./output/system/lib/modules  \;
find . -name 'zImage' -exec cp {} ./output/boot  \;
find . -name 'dt.img' -exec cp {} ./output/boot  \;
cd ./output/boot
base=0x00000000
offset=0x05000000
tags_addr=0x04800000
cmd_line="console=ttyHSL0,115200,n8 androidboot.hardware=g2 user_debug=31 msm_rtb.filter=0x0 mdss_mdp.panel=1:dsi:0:qcom,mdss_dsi_g2_lgd_cmd androidboot.selinux=permissive"
./mkbootimg --kernel ./zImage --ramdisk ./ramdisk.cpio.lz4 --cmdline "$cmd_line" --base $base --offset $offset --tags-addr $tags_addr --pagesize 2048 --dt ./dt.img -o boot.img
mv ./boot.img ../boot.img
cd ../
rm -rf ./boot/
zip -r KK-L01F-KERNEL-"$(date +"[20%y-%m%d]")".zip *
rm -f ./boot.img
cd ../
