#!/bin/bash
clear
rm -rf ./output/boot
rm -rf ./output/system/lib/modules
mkdir -p ./output/system/lib/modules
mkdir -p ./output/boot
./mkbootfs ./ramdisk | gzip > ramdisk.gz
mv ramdisk.gz ./output/boot
cd L01F11k
export CROSS_COMPILE=../arm-cortex_a8-linux-gnueabi-linaro_4.8.3-2014.01/bin/arm-cortex_a8-linux-gnueabi-
export USE_CCACHE=1
export ARCH=arm
export PATH=$PATH:tools/lz4demo
rm -f ./arch/arm/boot/dt.img
rm -f ./arch/arm/boot/*.dtb
make clean -j4
make -j8
cd ../
cp ./L01F11k/scripts/mkbootimg ./output/boot
find . -name '*.ko' -exec cp {} ./output/system/lib/modules  \;
find . -name 'zImage' -exec cp {} ./output/boot  \;
find . -name 'dt.img' -exec cp {} ./output/boot  \;
cd ./output/boot
base=0x00000000
offset=0x05000000
tags_addr=0x04800000
cmd_line="console=ttyHSL0,115200,n8 androidboot.hardware=g2 user_debug=31 msm_rtb.filter=0x0"
./mkbootimg --kernel ./zImage --ramdisk ./ramdisk.gz --cmdline "$cmd_line" --base $base --offset $offset --tags-addr $tags_addr --pagesize 2048 --dt ./dt.img -o boot.img
mv ./boot.img ../boot.img
cd ../
rm -rf ./boot/
zip -r G2NinjaKernel.zip *
